package modelos;

// Generated 1/05/2016 04:37:47 PM by Hibernate Tools 4.3.1.Final

/**
 * CatalogoCuenta generated by hbm2java
 */
public class CatalogoCuenta implements java.io.Serializable {

	private CatalogoCuentaId id;

	public CatalogoCuenta() {
	}

	public CatalogoCuenta(CatalogoCuentaId id) {
		this.id = id;
	}

	public CatalogoCuentaId getId() {
		return this.id;
	}

	public void setId(CatalogoCuentaId id) {
		this.id = id;
	}

}
