package modelos;
// Generated 20/05/2016 11:44:50 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetallePartida generated by hbm2java
 */
@Entity
@Table(name = "detalle_partida", catalog = "contabilidad")
public class DetallePartida implements java.io.Serializable {

	private long idDetalle;
	private Catalogo catalogo;
	private Partida partida;
	private byte debe;
	private byte haber;

	public DetallePartida() {
	}

	public DetallePartida(long idDetalle, Catalogo catalogo, Partida partida, byte debe, byte haber) {
		this.idDetalle = idDetalle;
		this.catalogo = catalogo;
		this.partida = partida;
		this.debe = debe;
		this.haber = haber;
	}

	@Id

	@Column(name = "id_detalle", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdDetalle() {
		return this.idDetalle;
	}

	public void setIdDetalle(long idDetalle) {
		this.idDetalle = idDetalle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cuenta", nullable = false)
	public Catalogo getCatalogo() {
		return this.catalogo;
	}

	public void setCatalogo(Catalogo catalogo) {
		this.catalogo = catalogo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_partida", nullable = false)
	public Partida getPartida() {
		return this.partida;
	}

	public void setPartida(Partida partida) {
		this.partida = partida;
	}

	@Column(name = "debe", nullable = false, precision = 2, scale = 0)
	public byte getDebe() {
		return this.debe;
	}

	public void setDebe(byte debe) {
		this.debe = debe;
	}

	@Column(name = "haber", nullable = false, precision = 2, scale = 0)
	public byte getHaber() {
		return this.haber;
	}

	public void setHaber(byte haber) {
		this.haber = haber;
	}

}
