package modelos;
// Generated 20/05/2016 11:44:50 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Partida generated by hbm2java
 */
@Entity
@Table(name = "partida", catalog = "contabilidad")
public class Partida implements java.io.Serializable {

	private long idPartida;
	private PeriocoContable periocoContable;
	private String concepto;
	private Date fecha;
	private Long noPartida;
	private Set<DetallePartida> detallePartidas = new HashSet<DetallePartida>(0);

	public Partida() {
	}

	public Partida(long idPartida, PeriocoContable periocoContable) {
		this.idPartida = idPartida;
		this.periocoContable = periocoContable;
	}

	public Partida(long idPartida, PeriocoContable periocoContable, String concepto, Date fecha, Long noPartida,
			Set<DetallePartida> detallePartidas) {
		this.idPartida = idPartida;
		this.periocoContable = periocoContable;
		this.concepto = concepto;
		this.fecha = fecha;
		this.noPartida = noPartida;
		this.detallePartidas = detallePartidas;
	}

	@Id

	@Column(name = "id_partida", unique = true, nullable = false, precision = 10, scale = 0)
	public long getIdPartida() {
		return this.idPartida;
	}

	public void setIdPartida(long idPartida) {
		this.idPartida = idPartida;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_periodo_contable", nullable = false)
	public PeriocoContable getPeriocoContable() {
		return this.periocoContable;
	}

	public void setPeriocoContable(PeriocoContable periocoContable) {
		this.periocoContable = periocoContable;
	}

	@Column(name = "concepto", length = 20)
	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "no_partida", precision = 10, scale = 0)
	public Long getNoPartida() {
		return this.noPartida;
	}

	public void setNoPartida(Long noPartida) {
		this.noPartida = noPartida;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partida")
	public Set<DetallePartida> getDetallePartidas() {
		return this.detallePartidas;
	}

	public void setDetallePartidas(Set<DetallePartida> detallePartidas) {
		this.detallePartidas = detallePartidas;
	}

}
